import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Document, Page as PdfPage, pdfjs } from 'react-pdf'

import { Button } from '../../components/Button'
import { ErrorBox } from '../../components/ErrorBox'
import { Input } from '../../components/Input'
import { Modal } from '../../components/Modal'
import { ListingTypePill } from '../../components/Pill'
import { Select } from '../../components/Select'
import { PageSpinner, Spinner } from '../../components/Spinner'
import { StarRating } from '../../components/StarRating'
import { StatusPill } from '../../components/StatusPill'
import { TextArea } from '../../components/TextArea'
import { useToast } from '../../components/Toast'
import { api } from '../../lib/api'
import { useAuth } from '../../lib/auth'
import {
  cx,
  formatDate,
  formatPrice,
  formatRating,
  initials,
  relativeTime,
  reportReasonLabel,
} from '../../lib/format'
import {
  REPORT_REASONS,
  type Conversation,
  type ConversationCreate,
  type Material,
  type Page as PageEnvelope,
  type Report,
  type ReportCreate,
  type ReportReason,
  type Review,
  type Transaction,
  type TransactionCreate,
} from '../../lib/types'

/*
 * PDF.js needs its worker as a separate file. Vite resolves this URL at build
 * time out of the `pdfjs-dist` copy that react-pdf depends on, so nothing is
 * fetched from a CDN.
 */
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url,
).toString()

/** Server-side slice size. Used for the copy only. */
const PREVIEW_PAGES = 3
const DEFAULT_RENTAL_DAYS = 14

// ---------------------------------------------------------------------------
// preview (FR 1.4)
// ---------------------------------------------------------------------------

/**
 * The preview is served by an authorising endpoint, so it cannot be handed to
 * `<Document file="/api/v1/...">` -- react-pdf would fetch it without the
 * bearer token. Pull the bytes through the API client and give the viewer an
 * object URL instead.
 *
 * Non-PDF uploads (scans, photos) get a downscaled first-page image from the
 * server rather than a PDF, so the content type decides how to render.
 */
function PreviewBody({ listingId, pageCount }: { listingId: string; pageCount?: number | null }) {
  const [objectUrl, setObjectUrl] = useState<string | null>(null)
  const [mime, setMime] = useState<string>('')
  const [error, setError] = useState<unknown>(null)
  const [numPages, setNumPages] = useState<number | null>(null)
  const [pageNumber, setPageNumber] = useState(1)
  const [width, setWidth] = useState(560)
  const frameRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    let cancelled = false
    let created: string | null = null

    api
      .blob(`/materials/${listingId}/preview`)
      .then(({ blob }) => {
        if (cancelled) return
        created = URL.createObjectURL(blob)
        setMime(blob.type)
        setObjectUrl(created)
      })
      .catch((cause: unknown) => {
        if (!cancelled) setError(cause)
      })

    return () => {
      cancelled = true
      if (created) URL.revokeObjectURL(created)
    }
  }, [listingId])

  // The page must be rendered at a real pixel width, which is the one genuinely
  // computed value on this screen.
  useEffect(() => {
    const element = frameRef.current
    if (!element) return
    const observer = new ResizeObserver((entries) => {
      const measured = entries[0]?.contentRect.width
      if (measured && measured > 0) setWidth(Math.floor(measured))
    })
    observer.observe(element)
    return () => observer.disconnect()
  }, [])

  if (error) {
    return <ErrorBox error={error} title="Could not load the preview" />
  }

  const isImage = mime.startsWith('image/')
  const total = numPages ?? 0

  return (
    <div>
      <p className="mb-3 rounded-lg bg-brand-50 px-3 py-2 text-xs leading-relaxed text-brand-900">
        This is a {PREVIEW_PAGES}-page preview, generated by the server when the file was uploaded.
        The full document is released only after a transaction completes.
        {pageCount ? ` The complete file has ${pageCount} pages.` : ''}
      </p>

      <div
        ref={frameRef}
        className="flex min-h-[24rem] items-center justify-center overflow-hidden rounded-lg bg-slate-100 p-2"
      >
        {!objectUrl ? (
          <div className="flex flex-col items-center gap-2 py-16 text-slate-400">
            <Spinner size="lg" label={null} />
            <p className="text-sm text-slate-500">Fetching the preview…</p>
          </div>
        ) : isImage ? (
          <img
            src={objectUrl}
            alt="First page of the uploaded material"
            className="max-h-[60vh] w-auto max-w-full rounded shadow-card"
          />
        ) : (
          <Document
            file={objectUrl}
            onLoadSuccess={(pdf) => {
              setNumPages(pdf.numPages)
              setPageNumber(1)
            }}
            onLoadError={(cause) => setError(cause)}
            loading={
              <div className="flex flex-col items-center gap-2 py-16 text-slate-400">
                <Spinner size="lg" label={null} />
                <p className="text-sm text-slate-500">Rendering…</p>
              </div>
            }
            error={<p className="py-16 text-sm text-slate-500">This preview could not be rendered.</p>}
          >
            <PdfPage
              pageNumber={pageNumber}
              width={width}
              renderTextLayer={false}
              renderAnnotationLayer={false}
              className="shadow-card"
            />
          </Document>
        )}
      </div>

      {!isImage && total > 0 ? (
        <div className="mt-3 flex items-center justify-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            disabled={pageNumber <= 1}
            onClick={() => setPageNumber((current) => Math.max(1, current - 1))}
          >
            Previous
          </Button>
          <p className="text-sm tabular-nums text-slate-600">
            Page {pageNumber} of {total}
          </p>
          <Button
            variant="ghost"
            size="sm"
            disabled={pageNumber >= total}
            onClick={() => setPageNumber((current) => Math.min(total, current + 1))}
          >
            Next
          </Button>
        </div>
      ) : null}
    </div>
  )
}

// ---------------------------------------------------------------------------
// small building blocks
// ---------------------------------------------------------------------------

function MetaRow({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5 border-b border-slate-100 py-2.5 last:border-b-0 sm:flex-row sm:gap-4">
      <dt className="w-40 shrink-0 text-xs font-medium uppercase tracking-wide text-slate-500">
        {label}
      </dt>
      <dd className="min-w-0 text-sm text-slate-800">{children}</dd>
    </div>
  )
}

// ---------------------------------------------------------------------------
// page
// ---------------------------------------------------------------------------

export default function ListingDetailPage() {
  const { id = '' } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const toast = useToast()
  const { user } = useAuth()

  const [previewOpen, setPreviewOpen] = useState(false)
  const [requestOpen, setRequestOpen] = useState(false)
  const [reportOpen, setReportOpen] = useState(false)

  // Request-modal fields (FR 3.4)
  const [rentalDays, setRentalDays] = useState(String(DEFAULT_RENTAL_DAYS))
  const [agreedPrice, setAgreedPrice] = useState('')

  // Report-modal fields (FR 3.5)
  const [reportReason, setReportReason] = useState<ReportReason>('INAPPROPRIATE')
  const [reportDetails, setReportDetails] = useState('')

  const listingQuery = useQuery({
    queryKey: ['materials', 'detail', id],
    queryFn: () => api.get<Material>(`/materials/${id}`),
    enabled: Boolean(id),
  })

  const reviewsQuery = useQuery({
    queryKey: ['materials', 'reviews', id],
    queryFn: () =>
      api.get<PageEnvelope<Review>>(`/materials/${id}/reviews`, {
        query: { page: 1, page_size: 10 },
      }),
    enabled: Boolean(id),
  })

  const listing = listingQuery.data

  // Seed the negotiated price from the asking price whenever the modal opens.
  const askingPrice = listing?.price
  useEffect(() => {
    if (requestOpen) {
      setAgreedPrice(askingPrice !== null && askingPrice !== undefined ? String(askingPrice) : '')
    }
  }, [requestOpen, askingPrice])

  const toggleWishlist = useMutation({
    mutationFn: () => {
      if (!listing) throw new Error('Listing not loaded')
      return listing.is_bookmarked
        ? api.del<void>(`/wishlist/items/${listing.listing_id}`)
        : api.post<void>('/wishlist/items', { listing_id: listing.listing_id })
    },
    onSuccess: async () => {
      const wasSaved = listing?.is_bookmarked
      await queryClient.invalidateQueries({ queryKey: ['materials'] })
      await queryClient.invalidateQueries({ queryKey: ['wishlist'] })
      toast.success(wasSaved ? 'Removed from your wishlist' : 'Saved to your wishlist')
    },
    onError: (cause) => toast.fromError(cause, 'Could not update your wishlist'),
  })

  const openConversation = useMutation({
    mutationFn: () => {
      if (!listing) throw new Error('Listing not loaded')
      const payload: ConversationCreate = {
        other_user_id: listing.uploader_id,
        listing_id: listing.listing_id,
      }
      return api.post<Conversation>('/conversations', payload)
    },
    onSuccess: (conversation) => navigate(`/messages/${conversation.conversation_id}`),
    onError: (cause) => toast.fromError(cause, 'Could not open a conversation'),
  })

  const createTransaction = useMutation({
    mutationFn: (payload: TransactionCreate) => api.post<Transaction>('/transactions', payload),
    onSuccess: async (transaction) => {
      setRequestOpen(false)
      await queryClient.invalidateQueries({ queryKey: ['materials'] })
      await queryClient.invalidateQueries({ queryKey: ['transactions'] })
      toast.success('Request sent', 'The owner has to accept before anything is handed over.')
      navigate(`/transactions/${transaction.transaction_id}`)
    },
    onError: (cause) => toast.fromError(cause, 'Could not send your request'),
  })

  const createReport = useMutation({
    mutationFn: (payload: ReportCreate) => api.post<Report>('/reports', payload),
    onSuccess: () => {
      setReportOpen(false)
      setReportDetails('')
      toast.success('Report filed', 'A moderator will review this listing.')
    },
    onError: (cause) => toast.fromError(cause, 'Could not file the report'),
  })

  if (listingQuery.isPending) return <PageSpinner label="Loading listing" />

  if (listingQuery.isError || !listing) {
    return (
      <ErrorBox
        error={listingQuery.error}
        title="Could not load this listing"
        onRetry={() => void listingQuery.refetch()}
      />
    )
  }

  const isOwner = user?.user_id === listing.uploader_id
  const isRent = listing.listing_type === 'RENT'
  const isPriced = listing.listing_type === 'SELL' || listing.listing_type === 'RENT'
  const tradable = listing.status === 'APPROVED'
  const reviews = reviewsQuery.data?.items ?? []

  const submitRequest = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault()
    const payload: TransactionCreate = {
      listing_id: listing.listing_id,
      agreed_price: isPriced && agreedPrice !== '' ? Number(agreedPrice) : null,
      rental_days: isRent ? Number(rentalDays) : null,
    }
    createTransaction.mutate(payload)
  }

  const submitReport = (event: FormEvent<HTMLFormElement>): void => {
    event.preventDefault()
    createReport.mutate({
      listing_id: listing.listing_id,
      reason: reportReason,
      details: reportDetails.trim() || null,
    })
  }

  return (
    <div className="space-y-6">
      <nav className="text-sm">
        <Link to="/" className="text-slate-500 hover:text-brand-700">
          ← Back to browse
        </Link>
      </nav>

      {/* A listing can be pulled or bounced back while someone is looking at it. */}
      {listing.status === 'REMOVED' || listing.status === 'REJECTED' ? (
        <div className="rounded-xl bg-red-50 p-4 ring-1 ring-inset ring-red-200">
          <p className="text-sm font-semibold text-red-900">
            {listing.status === 'REMOVED'
              ? 'A moderator removed this listing.'
              : 'This listing was rejected during moderation.'}
          </p>
          {listing.moderation_note ? (
            <p className="mt-1 text-sm leading-relaxed text-red-800">{listing.moderation_note}</p>
          ) : null}
        </div>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[1fr,20rem]">
        {/* ------------------------------------------------------------ main */}
        <div className="space-y-6">
          <header className="card p-6">
            <div className="flex flex-wrap items-center gap-2">
              <ListingTypePill type={listing.listing_type} />
              <StatusPill status={listing.status} kind="listing" />
              {listing.has_preview ? (
                <span className="pill bg-slate-100 text-slate-600 ring-slate-200">
                  {PREVIEW_PAGES}-page preview
                </span>
              ) : null}
            </div>

            <h1 className="mt-3 text-2xl font-semibold leading-tight tracking-tight text-slate-900">
              {listing.title}
            </h1>
            <p className="mt-1.5 text-sm text-slate-500">
              <span className="font-medium text-slate-700">{listing.course_code}</span>
              {' · '}
              {listing.department}
              {' · '}
              {listing.semester}
              {listing.edition ? ` · ${listing.edition}` : ''}
            </p>

            {listing.description ? (
              <p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-slate-700">
                {listing.description}
              </p>
            ) : (
              <p className="mt-4 text-sm italic text-slate-400">
                The uploader did not add a description.
              </p>
            )}
          </header>

          <section className="card p-6">
            <h2 className="text-base font-semibold text-slate-900">Details</h2>
            <dl className="mt-3">
              <MetaRow label="Course">{listing.course_code}</MetaRow>
              <MetaRow label="Department">{listing.department}</MetaRow>
              <MetaRow label="Semester">{listing.semester}</MetaRow>
              <MetaRow label="Edition">{listing.edition ?? '—'}</MetaRow>
              <MetaRow label="Campus">{listing.campus_name ?? listing.campus_id}</MetaRow>
              <MetaRow label="Pages">{listing.page_count ?? '—'}</MetaRow>
              <MetaRow label="Listed">
                {formatDate(listing.upload_date)}{' '}
                <span className="text-slate-400">({relativeTime(listing.upload_date)})</span>
              </MetaRow>
            </dl>
          </section>

          {/* --------------------------------------------------- FR 2.5 */}
          <section className="card p-6">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h2 className="text-base font-semibold text-slate-900">
                Reviews {reviewsQuery.data ? `(${reviewsQuery.data.total})` : ''}
              </h2>
              {typeof listing.avg_rating === 'number' ? (
                <StarRating value={listing.avg_rating} size="sm" count={listing.review_count} />
              ) : null}
            </div>

            {reviewsQuery.isPending ? (
              <div className="mt-4 h-20 animate-pulse rounded-lg bg-slate-100" />
            ) : reviews.length === 0 ? (
              <p className="mt-3 text-sm leading-relaxed text-slate-500">
                No reviews yet. Reviews can only be left by someone who completed a transaction for
                this listing.
              </p>
            ) : (
              <ul className="mt-3 divide-y divide-slate-100">
                {reviews.map((review) => (
                  <li key={review.review_id} className="py-4 first:pt-2 last:pb-0">
                    <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                      <StarRating value={review.rating} size="sm" count={null} />
                      <Link
                        to={`/users/${review.reviewer_id}`}
                        className="text-sm font-medium text-slate-800 hover:text-brand-700"
                      >
                        {review.reviewer_name ?? 'A student'}
                      </Link>
                      <span className="text-xs text-slate-400">
                        {relativeTime(review.created_at)}
                      </span>
                    </div>
                    {review.comment ? (
                      <p className="mt-1.5 text-sm leading-relaxed text-slate-600">
                        {review.comment}
                      </p>
                    ) : null}
                  </li>
                ))}
              </ul>
            )}
          </section>
        </div>

        {/* ----------------------------------------------------------- aside */}
        <aside className="space-y-4 lg:sticky lg:top-24 lg:self-start">
          <section className="card p-5">
            <p className="text-2xl font-semibold tracking-tight text-slate-900">
              {formatPrice(listing.listing_type, listing.price)}
            </p>
            {isRent ? (
              <p className="mt-1 text-xs text-slate-500">
                Rentals get a due date once the handoff is confirmed.
              </p>
            ) : null}

            <div className="mt-4 space-y-2">
              {listing.has_preview ? (
                <Button variant="ghost" fullWidth onClick={() => setPreviewOpen(true)}>
                  Preview first {PREVIEW_PAGES} pages
                </Button>
              ) : null}

              {isOwner ? (
                <Link to="/my-listings" className="btn btn-ghost w-full">
                  Manage in My listings
                </Link>
              ) : (
                <>
                  <Button
                    fullWidth
                    disabled={!tradable}
                    onClick={() => setRequestOpen(true)}
                    title={tradable ? undefined : 'This listing is not available right now'}
                  >
                    Request this item
                  </Button>

                  <Button
                    variant="ghost"
                    fullWidth
                    loading={openConversation.isPending}
                    onClick={() => openConversation.mutate()}
                  >
                    Message owner
                  </Button>

                  <Button
                    variant="ghost"
                    fullWidth
                    loading={toggleWishlist.isPending}
                    onClick={() => toggleWishlist.mutate()}
                    className={cx(listing.is_bookmarked && 'text-brand-700')}
                  >
                    {listing.is_bookmarked ? 'Saved to wishlist' : 'Save to wishlist'}
                  </Button>
                </>
              )}
            </div>

            {!tradable && !isOwner ? (
              <p className="mt-3 text-xs leading-relaxed text-slate-500">
                Only approved listings can be requested. This one is currently{' '}
                {listing.status.toLowerCase()}.
              </p>
            ) : null}
          </section>

          {/* ------------------------------------------------ uploader card */}
          <section className="card p-5">
            <h2 className="text-sm font-semibold text-slate-900">Listed by</h2>
            <div className="mt-3 flex items-center gap-3">
              <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brand-100 text-sm font-semibold text-brand-800">
                {initials(listing.uploader_name)}
              </span>
              <div className="min-w-0">
                <Link
                  to={`/users/${listing.uploader_id}`}
                  className="block truncate text-sm font-medium text-slate-900 hover:text-brand-700"
                >
                  {listing.uploader_name ?? 'Unknown student'}
                </Link>
                <span className="mt-0.5 flex items-center gap-1.5">
                  <StarRating value={listing.uploader_rating} size="sm" count={null} />
                  <span className="text-xs text-slate-500">
                    {formatRating(listing.uploader_rating)}
                  </span>
                </span>
              </div>
            </div>
            <Link
              to={`/users/${listing.uploader_id}`}
              className="mt-3 inline-block text-xs font-medium text-brand-700 hover:text-brand-800"
            >
              See their rating and reviews →
            </Link>
          </section>

          {!isOwner ? (
            <button
              type="button"
              onClick={() => setReportOpen(true)}
              className="w-full text-center text-xs font-medium text-slate-500 hover:text-state-rejected"
            >
              Report this listing
            </button>
          ) : null}
        </aside>
      </div>

      {/* --------------------------------------------------- preview modal */}
      <Modal
        open={previewOpen}
        onClose={() => setPreviewOpen(false)}
        size="xl"
        title={listing.title}
        description={`${listing.course_code} · ${listing.department}`}
      >
        {previewOpen ? (
          <PreviewBody listingId={listing.listing_id} pageCount={listing.page_count} />
        ) : null}
      </Modal>

      {/* --------------------------------------------------- request modal */}
      <Modal
        open={requestOpen}
        onClose={() => setRequestOpen(false)}
        title="Request this item"
        description={
          isRent
            ? 'Tell the owner how long you need it for. They confirm before any handoff.'
            : 'The owner reviews your request before anything is exchanged.'
        }
        dismissable={!createTransaction.isPending}
        footer={
          <>
            <Button
              variant="ghost"
              onClick={() => setRequestOpen(false)}
              disabled={createTransaction.isPending}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              form="request-form"
              loading={createTransaction.isPending}
            >
              Send request
            </Button>
          </>
        }
      >
        <form id="request-form" className="space-y-4" onSubmit={submitRequest}>
          <div className="rounded-lg bg-slate-50 p-3 text-sm ring-1 ring-inset ring-slate-200">
            <p className="font-medium text-slate-900">{listing.title}</p>
            <p className="mt-0.5 text-xs text-slate-500">
              {listing.course_code} · asking {formatPrice(listing.listing_type, listing.price)}
            </p>
          </div>

          {isRent ? (
            <Input
              label="Rental length in days"
              type="number"
              min={1}
              max={180}
              required
              value={rentalDays}
              hint="The due date is counted from the day the handoff is confirmed."
              onChange={(event) => setRentalDays(event.target.value)}
            />
          ) : isPriced ? (
            <Input
              label="Price you are offering"
              type="number"
              min={0}
              step="1"
              required
              prefix="৳"
              value={agreedPrice}
              hint="Defaults to the asking price. Change it if you have agreed something else."
              onChange={(event) => setAgreedPrice(event.target.value)}
            />
          ) : (
            <p className="rounded-lg bg-slate-50 px-3 py-2 text-sm text-slate-600 ring-1 ring-inset ring-slate-200">
              {listing.listing_type === 'FREE'
                ? 'This item is being given away, so there is nothing to agree on price.'
                : 'This is an exchange — arrange what you are swapping in the chat.'}
            </p>
          )}

          {/* `TransactionCreate` carries no message field -- the request is the
              listing, the price and the rental length, nothing else. Arranging
              the handoff happens in the thread. */}
          <p className="text-xs leading-relaxed text-slate-500">
            Sending this does not include a note. Use “Message owner” to agree when and where to
            meet.
          </p>
        </form>
      </Modal>

      {/* ---------------------------------------------------- report modal */}
      <Modal
        open={reportOpen}
        onClose={() => setReportOpen(false)}
        title="Report this listing"
        description="Reports go to the moderation queue. You can file one report per listing."
        dismissable={!createReport.isPending}
        footer={
          <>
            <Button
              variant="ghost"
              onClick={() => setReportOpen(false)}
              disabled={createReport.isPending}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              form="report-form"
              variant="danger"
              loading={createReport.isPending}
            >
              Submit report
            </Button>
          </>
        }
      >
        <form id="report-form" className="space-y-4" onSubmit={submitReport}>
          <Select
            label="Reason"
            required
            value={reportReason}
            onChange={(event) => setReportReason(event.target.value as ReportReason)}
            options={REPORT_REASONS.map((reason) => ({
              value: reason,
              label: reportReasonLabel(reason),
            }))}
          />

          <TextArea
            label="What is wrong with it?"
            rows={4}
            maxLength={1000}
            showCount
            value={reportDetails}
            placeholder="Be specific — it helps a moderator act on this quickly."
            onChange={(event) => setReportDetails(event.target.value)}
          />
        </form>
      </Modal>
    </div>
  )
}
