"""Initial NoteVault schema.

Hand-written rather than autogenerated, for two reasons:

* SQLModel cannot express CHECK constraints, partial uniqueness or FTS5
  virtual tables, and those are where the real invariants live.
* The DDL below is the canonical schema; the SQLModel definitions in
  ``app/models/tables.py`` mirror it, so the two cannot drift.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# identity & place
# ---------------------------------------------------------------------------

CAMPUSES = """
CREATE TABLE campuses (
    campus_id     TEXT PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    location      TEXT NOT NULL
)
"""

USERS = """
CREATE TABLE users (
    user_id       TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'STUDENT'
                  CHECK (role IN ('STUDENT','ADMIN')),
    campus_id     TEXT NOT NULL REFERENCES campuses(campus_id),
    rating_avg    REAL NOT NULL DEFAULT 0,
    rating_count  INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL
)
"""

REFRESH_TOKENS = """
CREATE TABLE refresh_tokens (
    token_id    TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TEXT NOT NULL,
    revoked_at  TEXT,
    created_at  TEXT NOT NULL
)
"""

# ---------------------------------------------------------------------------
# module 1 -- listings
# ---------------------------------------------------------------------------

STUDY_MATERIALS = """
CREATE TABLE study_materials (
    listing_id       TEXT PRIMARY KEY,
    uploader_id      TEXT NOT NULL REFERENCES users(user_id),
    campus_id        TEXT NOT NULL REFERENCES campuses(campus_id),
    title            TEXT NOT NULL,
    description      TEXT,
    course_code      TEXT NOT NULL,
    course_code_norm TEXT NOT NULL,
    department       TEXT NOT NULL,
    semester         TEXT NOT NULL,
    edition          TEXT,
    listing_type     TEXT NOT NULL
                     CHECK (listing_type IN ('SELL','RENT','EXCHANGE','FREE')),
    price            REAL,
    status           TEXT NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING','APPROVED','REJECTED',
                                       'RESERVED','COMPLETED','REMOVED')),
    file_path        TEXT NOT NULL,
    preview_path     TEXT,
    page_count       INTEGER,
    file_hash        TEXT NOT NULL,
    upload_date      TEXT NOT NULL,
    moderated_by     TEXT REFERENCES users(user_id),
    moderated_at     TEXT,
    moderation_note  TEXT,
    CHECK ((listing_type IN ('EXCHANGE','FREE') AND price IS NULL)
        OR (listing_type IN ('SELL','RENT')     AND price IS NOT NULL AND price >= 0))
)
"""

# FTS5 external-content index backing FR 1.2 keyword search. `content=` means
# the index stores no copy of the text; the triggers below keep it in step.
MATERIALS_FTS = """
CREATE VIRTUAL TABLE materials_fts USING fts5(
    title,
    course_code,
    department,
    description,
    content='study_materials',
    content_rowid='rowid'
)
"""

FTS_TRIGGERS = [
    """
    CREATE TRIGGER study_materials_ai AFTER INSERT ON study_materials BEGIN
        INSERT INTO materials_fts(rowid, title, course_code, department, description)
        VALUES (new.rowid, new.title, new.course_code, new.department, new.description);
    END
    """,
    """
    CREATE TRIGGER study_materials_ad AFTER DELETE ON study_materials BEGIN
        INSERT INTO materials_fts(materials_fts, rowid, title, course_code, department, description)
        VALUES ('delete', old.rowid, old.title, old.course_code, old.department, old.description);
    END
    """,
    """
    CREATE TRIGGER study_materials_au AFTER UPDATE ON study_materials BEGIN
        INSERT INTO materials_fts(materials_fts, rowid, title, course_code, department, description)
        VALUES ('delete', old.rowid, old.title, old.course_code, old.department, old.description);
        INSERT INTO materials_fts(rowid, title, course_code, department, description)
        VALUES (new.rowid, new.title, new.course_code, new.department, new.description);
    END
    """,
]

# ---------------------------------------------------------------------------
# module 2 -- community
# ---------------------------------------------------------------------------

REQUESTS = """
CREATE TABLE requests (
    request_id       TEXT PRIMARY KEY,
    requester_id     TEXT NOT NULL REFERENCES users(user_id),
    course_code      TEXT NOT NULL,
    course_code_norm TEXT NOT NULL,
    department       TEXT,
    edition          TEXT,
    listing_type     TEXT CHECK (listing_type IN ('SELL','RENT','EXCHANGE','FREE')),
    max_price        REAL,
    campus_id        TEXT REFERENCES campuses(campus_id),
    description      TEXT,
    status           TEXT NOT NULL DEFAULT 'OPEN'
                     CHECK (status IN ('OPEN','MATCHED','CLOSED')),
    created_at       TEXT NOT NULL
)
"""

WISHLISTS = """
CREATE TABLE wishlists (
    wishlist_id  TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL UNIQUE REFERENCES users(user_id) ON DELETE CASCADE
)
"""

WISHLIST_ITEMS = """
CREATE TABLE wishlist_items (
    wishlist_id  TEXT NOT NULL REFERENCES wishlists(wishlist_id) ON DELETE CASCADE,
    listing_id   TEXT NOT NULL REFERENCES study_materials(listing_id) ON DELETE CASCADE,
    added_at     TEXT NOT NULL,
    PRIMARY KEY (wishlist_id, listing_id)
)
"""

CONVERSATIONS = """
CREATE TABLE conversations (
    conversation_id TEXT PRIMARY KEY,
    user_a_id       TEXT NOT NULL REFERENCES users(user_id),
    user_b_id       TEXT NOT NULL REFERENCES users(user_id),
    listing_id      TEXT REFERENCES study_materials(listing_id),
    created_at      TEXT NOT NULL,
    last_message_at TEXT,
    CHECK (user_a_id < user_b_id),
    UNIQUE (user_a_id, user_b_id, listing_id)
)
"""

MESSAGES = """
CREATE TABLE messages (
    message_id      TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL REFERENCES conversations(conversation_id) ON DELETE CASCADE,
    sender_id       TEXT NOT NULL REFERENCES users(user_id),
    content         TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    read_at         TEXT
)
"""

# ---------------------------------------------------------------------------
# module 3 -- transactions & trust
# ---------------------------------------------------------------------------

TRANSACTIONS = """
CREATE TABLE transactions (
    transaction_id   TEXT PRIMARY KEY,
    listing_id       TEXT NOT NULL REFERENCES study_materials(listing_id),
    buyer_id         TEXT NOT NULL REFERENCES users(user_id),
    seller_id        TEXT NOT NULL REFERENCES users(user_id),
    transaction_type TEXT NOT NULL
                     CHECK (transaction_type IN ('SELL','RENT','EXCHANGE','FREE')),
    agreed_price     REAL,
    status           TEXT NOT NULL DEFAULT 'REQUESTED'
                     CHECK (status IN ('REQUESTED','ACCEPTED','AWAITING_HANDOFF',
                                       'COMPLETED','CANCELLED')),
    transaction_date TEXT NOT NULL,
    completed_at     TEXT,
    CHECK (buyer_id <> seller_id)
)
"""

RENTALS = """
CREATE TABLE rentals (
    rental_id           TEXT PRIMARY KEY,
    transaction_id      TEXT NOT NULL UNIQUE REFERENCES transactions(transaction_id),
    start_date          TEXT NOT NULL,
    due_date            TEXT NOT NULL,
    returned            INTEGER NOT NULL DEFAULT 0,
    returned_at         TEXT,
    last_reminder_stage TEXT NOT NULL DEFAULT 'NONE'
                        CHECK (last_reminder_stage IN ('NONE','T_MINUS_3','T_MINUS_1','OVERDUE'))
)
"""

QR_HANDOFFS = """
CREATE TABLE qr_handoffs (
    handoff_id         TEXT PRIMARY KEY,
    transaction_id     TEXT NOT NULL UNIQUE REFERENCES transactions(transaction_id),
    token_hash         TEXT NOT NULL,
    nonce              TEXT NOT NULL UNIQUE,
    manual_code        TEXT NOT NULL,
    expires_at         TEXT NOT NULL,
    consumed_at        TEXT,
    verified_by_buyer  INTEGER NOT NULL DEFAULT 0,
    verified_by_seller INTEGER NOT NULL DEFAULT 0,
    verified_at        TEXT
)
"""

REPORTS = """
CREATE TABLE reports (
    report_id       TEXT PRIMARY KEY,
    reporter_id     TEXT NOT NULL REFERENCES users(user_id),
    listing_id      TEXT NOT NULL REFERENCES study_materials(listing_id),
    reason          TEXT NOT NULL
                    CHECK (reason IN ('INAPPROPRIATE','FAKE','COPYRIGHT','SPAM','OTHER')),
    details         TEXT,
    status          TEXT NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','RESOLVED','DISMISSED')),
    created_at      TEXT NOT NULL,
    resolved_by     TEXT REFERENCES users(user_id),
    resolved_at     TEXT,
    resolution_note TEXT,
    UNIQUE (reporter_id, listing_id)
)
"""

REVIEWS = """
CREATE TABLE reviews (
    review_id      TEXT PRIMARY KEY,
    transaction_id TEXT NOT NULL REFERENCES transactions(transaction_id),
    reviewer_id    TEXT NOT NULL REFERENCES users(user_id),
    reviewee_id    TEXT NOT NULL REFERENCES users(user_id),
    listing_id     TEXT NOT NULL REFERENCES study_materials(listing_id),
    rating         INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment        TEXT,
    created_at     TEXT NOT NULL,
    UNIQUE (transaction_id, reviewer_id),
    CHECK (reviewer_id <> reviewee_id)
)
"""

# ---------------------------------------------------------------------------
# cross-cutting
# ---------------------------------------------------------------------------

NOTIFICATIONS = """
CREATE TABLE notifications (
    notification_id TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    type            TEXT NOT NULL,
    message         TEXT NOT NULL,
    ref_type        TEXT,
    ref_id          TEXT,
    is_read         INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL
)
"""

COURSE_DEMAND_EVENTS = """
CREATE TABLE course_demand_events (
    event_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    course_code_norm TEXT NOT NULL,
    campus_id        TEXT REFERENCES campuses(campus_id),
    event_type       TEXT NOT NULL
                     CHECK (event_type IN ('SEARCH','VIEW','REQUEST','WISHLIST_ADD')),
    created_at       TEXT NOT NULL
)
"""

INDEXES = [
    "CREATE INDEX idx_users_campus       ON users(campus_id)",
    "CREATE INDEX idx_refresh_user       ON refresh_tokens(user_id)",
    "CREATE INDEX idx_materials_course   ON study_materials(course_code_norm, status)",
    "CREATE INDEX idx_materials_browse   ON study_materials(status, campus_id, upload_date DESC)",
    "CREATE INDEX idx_materials_uploader ON study_materials(uploader_id)",
    "CREATE INDEX idx_materials_hash     ON study_materials(file_hash)",
    "CREATE INDEX idx_requests_match     ON requests(course_code_norm, status)",
    "CREATE INDEX idx_requests_owner     ON requests(requester_id)",
    "CREATE INDEX idx_conv_a             ON conversations(user_a_id, last_message_at DESC)",
    "CREATE INDEX idx_conv_b             ON conversations(user_b_id, last_message_at DESC)",
    "CREATE INDEX idx_messages_thread    ON messages(conversation_id, timestamp)",
    "CREATE INDEX idx_tx_buyer           ON transactions(buyer_id, transaction_date DESC)",
    "CREATE INDEX idx_tx_seller          ON transactions(seller_id, transaction_date DESC)",
    "CREATE INDEX idx_tx_listing         ON transactions(listing_id)",
    "CREATE INDEX idx_rentals_due        ON rentals(returned, due_date)",
    "CREATE INDEX idx_reports_queue      ON reports(status, created_at)",
    "CREATE INDEX idx_reviews_reviewee   ON reviews(reviewee_id)",
    "CREATE INDEX idx_reviews_listing    ON reviews(listing_id)",
    "CREATE INDEX idx_notif_user         ON notifications(user_id, is_read, created_at DESC)",
    "CREATE INDEX idx_demand             ON course_demand_events(course_code_norm, created_at)",
]

TABLES_IN_ORDER = [
    CAMPUSES,
    USERS,
    REFRESH_TOKENS,
    STUDY_MATERIALS,
    REQUESTS,
    WISHLISTS,
    WISHLIST_ITEMS,
    CONVERSATIONS,
    MESSAGES,
    TRANSACTIONS,
    RENTALS,
    QR_HANDOFFS,
    REPORTS,
    REVIEWS,
    NOTIFICATIONS,
    COURSE_DEMAND_EVENTS,
]

DROP_ORDER = [
    "course_demand_events",
    "notifications",
    "reviews",
    "reports",
    "qr_handoffs",
    "rentals",
    "transactions",
    "messages",
    "conversations",
    "wishlist_items",
    "wishlists",
    "requests",
    "study_materials",
    "refresh_tokens",
    "users",
    "campuses",
]


def upgrade() -> None:
    for statement in TABLES_IN_ORDER:
        op.execute(statement)
    op.execute(MATERIALS_FTS)
    for trigger in FTS_TRIGGERS:
        op.execute(trigger)
    for index in INDEXES:
        op.execute(index)


def downgrade() -> None:
    for trigger in ("study_materials_au", "study_materials_ad", "study_materials_ai"):
        op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
    op.execute("DROP TABLE IF EXISTS materials_fts")
    for table in DROP_ORDER:
        op.execute(f"DROP TABLE IF EXISTS {table}")
